<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PembayaranTanggal Event Sabtu , 06 Juli_ecc7c3</name>
   <tag></tag>
   <elementGuidId>1cfc0e0c-0163-4be0-9dcd-eba1162b712a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07a09388-392b-4e9b-a493-4134ad3f0c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-order</value>
      <webElementGuid>27126f6c-e0ed-4ead-9f4d-5e2be623fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PembayaranTanggal Event Sabtu , 06 Juli 2024 Event Music 2024Status PembayaranMenunggu Pembayaran Tiket KamuGOLDRp 20.0001x GOLDRp 20.000Biaya LayananRp 2.540DiskonRp 0Total PembayaranRp 22.540</value>
      <webElementGuid>dfe43718-ea53-4d91-b042-98707f671ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-page&quot;]/div[@class=&quot;card-page&quot;]/div[@class=&quot;form-order&quot;]</value>
      <webElementGuid>a2ea62f6-17a8-4d04-8d1f-c58e380249f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Beli/iframe_Beli Tiketmu Sekarang_eventiframe</value>
      <webElementGuid>51d51cbd-de58-439c-a81e-54d5bf5bc07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div</value>
      <webElementGuid>dbc03549-068c-4b28-b0b4-8c62a3f5fd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>19007f47-aed6-4983-9b64-b5ed5d4e7fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PembayaranTanggal Event Sabtu , 06 Juli 2024 Event Music 2024Status PembayaranMenunggu Pembayaran Tiket KamuGOLDRp 20.0001x GOLDRp 20.000Biaya LayananRp 2.540DiskonRp 0Total PembayaranRp 22.540' or . = 'PembayaranTanggal Event Sabtu , 06 Juli 2024 Event Music 2024Status PembayaranMenunggu Pembayaran Tiket KamuGOLDRp 20.0001x GOLDRp 20.000Biaya LayananRp 2.540DiskonRp 0Total PembayaranRp 22.540')]</value>
      <webElementGuid>035090a0-8941-4790-a0b3-4927c02be776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
