<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Beli Tiketmu Sekarang_eventiframe</name>
   <tag></tag>
   <elementGuidId>4e8a5a92-1f49-499a-afab-01153353d51f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='eventiframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eventiframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9f6ee8d6-163d-4121-b21e-e0c809b45e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventiframe</value>
      <webElementGuid>5fde96e8-ec9f-49be-bf71-80d178ad8eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ticket-dev2.metalgo.co/event/event-music-2024?platform_key=TICKET_WEB</value>
      <webElementGuid>c40e0533-6b53-4c17-ae9f-a390d32f6bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventiframe&quot;)</value>
      <webElementGuid>f80c8671-b3b9-4f94-b15e-6a232a9e0ef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='eventiframe']</value>
      <webElementGuid>c9e0107b-0685-4dbc-92b5-ef8fa4eeb7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframeWrp']/iframe</value>
      <webElementGuid>81182863-431f-4cf6-8232-e0d20d6ef162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli Tiketmu Sekarang!'])[1]/following::iframe[1]</value>
      <webElementGuid>34c4681b-304f-4836-b42f-e9419f1120ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETOR PROMOTOR'])[1]/following::iframe[1]</value>
      <webElementGuid>6b6a37b6-f081-46e2-a09b-3556339b119c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETOR PROMOTOR'])[2]/preceding::iframe[1]</value>
      <webElementGuid>7e5115e2-601e-4c6a-9d98-498f875531e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::iframe[1]</value>
      <webElementGuid>0353983a-26af-4911-8850-450aae5b54e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>211b68d1-9604-45d3-9c9a-d42f0bcac3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'eventiframe' and @src = 'https://ticket-dev2.metalgo.co/event/event-music-2024?platform_key=TICKET_WEB']</value>
      <webElementGuid>f477ebbf-98e7-4c3d-91e3-b26bf91a082b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
