<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Data Pengunjung_back-icon</name>
   <tag></tag>
   <elementGuidId>249f2951-ddd8-4298-8cbb-494964eda8ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.back-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68d7c856-8b39-41ec-a4d6-f509d564633d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAACXBIWXMAACxLAAAsSwGlPZapAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJ4SURBVHgB7dwxctNAGIbhX3ZDZ8luKB27oQNOAHSUKblFkhs4JyAlVEBJFzqogI4O6C2jG0h0NLb4d/AMydhJZMta7WrfZyZjO6PMxN9nyTvSrkQAAAAAAAAAAAAAAAAAdE0kHhmPx3Gv1zuJouhUX8ZlWf7Q5xdpmr4TT/XFE+vwP2vgL/TlPfM7fX5fH46TJPmd5/k38ZAXe8CV8B/dsEmxXC6PsiwrxDM9cVyF8I1Yf56Ih5wuoGL4XnO2gD3C/ykecrKAXcPX7c71+J+Jh5z7Et4n/Pl8PhNPOVVAaOEbzhQQYviGEwWEGr7RegEhh2+0WkDo4RutFUD4/7RSAOH/Z70Awr/OagGEv8laAYS/nbVzQYS/nZUCJpPJS8LfrvFDkB56xv1+/5d0y6VegTs7xBnYxvcADX8m3XOs7+u7+XBJTY0XoIeUh9JNsZbwRmpqvICyLDt7OVHVfm/OX5R3XCw12dgDMumuD1KTjT2g9j/pKDMX6VRqsjEKeivdYiZ/fdHwHx9iGGrlVMR0Or3Qh5Mq2+oha7ZYLM4lEFbmhuZ5/nE4HB5JhVGDDlufJkli/uarBMDa5FwN9JISNlmdHU0Jm6xPT6eE61pZH7AuwRTw4K5tu15Caws0BoPBJw33+XqRxa26XEJrBRRF8UdLeB96Ca0uUaIEB9aIhV6CE4v0Qi7BmVWSoZbg1DLVEEtwbp3wniWwTvjQdpzIxTrhQzNhrlarZ+Z2BBU2Z51wE3YswUvOX5TfoQQvv4i9mBVxVwnrdcLeHf8Nb+6WYkZHOtJ5PRqNIi0i1tDNHVPMyOcsTdNXAgAAAAAAAAAAAAAAAACO+At220OBlN8Y9wAAAABJRU5ErkJggg==</value>
      <webElementGuid>d015f3b6-2b91-4066-b785-71925266addd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-icon</value>
      <webElementGuid>181c9a33-14b1-4dee-a530-9924f1684f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-page&quot;]/div[@class=&quot;wrap-header&quot;]/div[@class=&quot;title&quot;]/div[@class=&quot;row m-0 p-0&quot;]/div[@class=&quot;col p-0 m-0&quot;]/a[@class=&quot;text-black&quot;]/img[@class=&quot;back-icon&quot;]</value>
      <webElementGuid>95ee13e6-2d2b-4dde-bc1e-bf3184d2d4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Beli/iframe_Beli Tiketmu Sekarang_eventiframe</value>
      <webElementGuid>cba35acd-dd9d-44e3-9472-783d8271926c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/a/img</value>
      <webElementGuid>88ac179b-0e2e-421c-819d-54f0865d3bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAACXBIWXMAACxLAAAsSwGlPZapAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJ4SURBVHgB7dwxctNAGIbhX3ZDZ8luKB27oQNOAHSUKblFkhs4JyAlVEBJFzqogI4O6C2jG0h0NLb4d/AMydhJZMta7WrfZyZjO6PMxN9nyTvSrkQAAAAAAAAAAAAAAAAAdE0kHhmPx3Gv1zuJouhUX8ZlWf7Q5xdpmr4TT/XFE+vwP2vgL/TlPfM7fX5fH46TJPmd5/k38ZAXe8CV8B/dsEmxXC6PsiwrxDM9cVyF8I1Yf56Ih5wuoGL4XnO2gD3C/ykecrKAXcPX7c71+J+Jh5z7Et4n/Pl8PhNPOVVAaOEbzhQQYviGEwWEGr7RegEhh2+0WkDo4RutFUD4/7RSAOH/Z70Awr/OagGEv8laAYS/nbVzQYS/nZUCJpPJS8LfrvFDkB56xv1+/5d0y6VegTs7xBnYxvcADX8m3XOs7+u7+XBJTY0XoIeUh9JNsZbwRmpqvICyLDt7OVHVfm/OX5R3XCw12dgDMumuD1KTjT2g9j/pKDMX6VRqsjEKeivdYiZ/fdHwHx9iGGrlVMR0Or3Qh5Mq2+oha7ZYLM4lEFbmhuZ5/nE4HB5JhVGDDlufJkli/uarBMDa5FwN9JISNlmdHU0Jm6xPT6eE61pZH7AuwRTw4K5tu15Caws0BoPBJw33+XqRxa26XEJrBRRF8UdLeB96Ca0uUaIEB9aIhV6CE4v0Qi7BmVWSoZbg1DLVEEtwbp3wniWwTvjQdpzIxTrhQzNhrlarZ+Z2BBU2Z51wE3YswUvOX5TfoQQvv4i9mBVxVwnrdcLeHf8Nb+6WYkZHOtJ5PRqNIi0i1tDNHVPMyOcsTdNXAgAAAAAAAAAAAAAAAACO+At220OBlN8Y9wAAAABJRU5ErkJggg==')]</value>
      <webElementGuid>6eaeb06e-5722-4508-9138-2507847a234c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>58af4ac5-367f-4b5f-8777-ab5b508d951c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAACXBIWXMAACxLAAAsSwGlPZapAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJ4SURBVHgB7dwxctNAGIbhX3ZDZ8luKB27oQNOAHSUKblFkhs4JyAlVEBJFzqogI4O6C2jG0h0NLb4d/AMydhJZMta7WrfZyZjO6PMxN9nyTvSrkQAAAAAAAAAAAAAAAAAdE0kHhmPx3Gv1zuJouhUX8ZlWf7Q5xdpmr4TT/XFE+vwP2vgL/TlPfM7fX5fH46TJPmd5/k38ZAXe8CV8B/dsEmxXC6PsiwrxDM9cVyF8I1Yf56Ih5wuoGL4XnO2gD3C/ykecrKAXcPX7c71+J+Jh5z7Et4n/Pl8PhNPOVVAaOEbzhQQYviGEwWEGr7RegEhh2+0WkDo4RutFUD4/7RSAOH/Z70Awr/OagGEv8laAYS/nbVzQYS/nZUCJpPJS8LfrvFDkB56xv1+/5d0y6VegTs7xBnYxvcADX8m3XOs7+u7+XBJTY0XoIeUh9JNsZbwRmpqvICyLDt7OVHVfm/OX5R3XCw12dgDMumuD1KTjT2g9j/pKDMX6VRqsjEKeivdYiZ/fdHwHx9iGGrlVMR0Or3Qh5Mq2+oha7ZYLM4lEFbmhuZ5/nE4HB5JhVGDDlufJkli/uarBMDa5FwN9JISNlmdHU0Jm6xPT6eE61pZH7AuwRTw4K5tu15Caws0BoPBJw33+XqRxa26XEJrBRRF8UdLeB96Ca0uUaIEB9aIhV6CE4v0Qi7BmVWSoZbg1DLVEEtwbp3wniWwTvjQdpzIxTrhQzNhrlarZ+Z2BBU2Z51wE3YswUvOX5TfoQQvv4i9mBVxVwnrdcLeHf8Nb+6WYkZHOtJ5PRqNIi0i1tDNHVPMyOcsTdNXAgAAAAAAAAAAAAAAAACO+At220OBlN8Y9wAAAABJRU5ErkJggg==']</value>
      <webElementGuid>1f554179-12a3-4561-a7ee-f8cf9e15d084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
