<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Beli Tiketmu Sekarang_eventiframe (1)</name>
   <tag></tag>
   <elementGuidId>4c670607-608b-41d9-b9ab-6c81becaa99b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventiframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='eventiframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1cedc2fb-4fa8-4e7a-9a74-1ae86c8dd616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventiframe</value>
      <webElementGuid>d8a84942-46f3-4efa-8cf7-bedf74523459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ticket-dev2.metalgo.co/event/event-music-2024?platform_key=TICKET_WEB</value>
      <webElementGuid>135f9e2e-c593-4005-b697-dc327b2a7f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventiframe&quot;)</value>
      <webElementGuid>b8744826-735a-47c1-b3ff-f32f08cf7f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='eventiframe']</value>
      <webElementGuid>80a78485-f108-4806-aea1-770f1fa04ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframeWrp']/iframe</value>
      <webElementGuid>3bf40bf2-4267-45a6-90d4-0dbf044194da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli Tiketmu Sekarang!'])[1]/following::iframe[1]</value>
      <webElementGuid>5b22c7dd-40cb-4a95-a492-b100f1da725a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETOR PROMOTOR'])[1]/following::iframe[1]</value>
      <webElementGuid>afdf5a6a-b05b-4c4b-8dc4-5c1a1dea8bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETOR PROMOTOR'])[2]/preceding::iframe[1]</value>
      <webElementGuid>5b734d15-7dd6-4518-843a-c89ea92f64fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::iframe[1]</value>
      <webElementGuid>7ffce459-9cf3-4b44-a684-280ae4794d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>994c91cd-46c2-4cc8-b64d-85c4b131b40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'eventiframe' and @src = 'https://ticket-dev2.metalgo.co/event/event-music-2024?platform_key=TICKET_WEB']</value>
      <webElementGuid>c3d2cfaa-b567-4624-bf6c-754411d2768a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
