<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Beli Tiketmu Sekarang_eventiframe</name>
   <tag></tag>
   <elementGuidId>99a06097-9a88-4068-b999-438d92072ff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventiframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='eventiframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>026596d8-fa36-45ad-a205-605badbb1fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventiframe</value>
      <webElementGuid>477717c1-b3e5-4a56-af59-ead1817352e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ticket-dev2.metalgo.co/event/event-music-2024?platform_key=TICKET_WEB</value>
      <webElementGuid>2e3a8e4f-8f10-4103-a535-bce2d2526e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventiframe&quot;)</value>
      <webElementGuid>45ec9dd3-8df5-4664-9907-7fa227001841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='eventiframe']</value>
      <webElementGuid>d503210b-f23d-40c4-a927-029fdbb0dad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframeWrp']/iframe</value>
      <webElementGuid>ded4a5da-e290-4464-b6f0-04ec69e53f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli Tiketmu Sekarang!'])[1]/following::iframe[1]</value>
      <webElementGuid>43dd7dcb-1670-4c30-b08a-196d3c97d89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETOR PROMOTOR'])[1]/following::iframe[1]</value>
      <webElementGuid>4abb539a-3e8b-43b6-9c67-934607cf2b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETOR PROMOTOR'])[2]/preceding::iframe[1]</value>
      <webElementGuid>eb4e0ab0-f005-4824-bb6c-aab317498eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::iframe[1]</value>
      <webElementGuid>7e1314c8-9ad7-40f6-8814-e0058f44d10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6499811d-e4b1-423a-8372-5c0a76ba88ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'eventiframe' and @src = 'https://ticket-dev2.metalgo.co/event/event-music-2024?platform_key=TICKET_WEB']</value>
      <webElementGuid>0ecd08be-944e-4bbf-8309-b81084964b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
