<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Indonesia_sbmtbutton</name>
   <tag></tag>
   <elementGuidId>3abda09f-6b67-44c9-9ffd-cf04c9ea5c18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sbmtbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sbmtbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6eacee19-5cfa-4d0b-a088-881294677bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sbmtbutton</value>
      <webElementGuid>7d789ce5-660e-4d7c-a62d-3b3873b0b779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dde4b728-6444-4bd1-b79d-bd3564fa9241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pay Now</value>
      <webElementGuid>7a23ee2c-4eb7-4b4b-a18f-1c505944a0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sbmtbutton&quot;)</value>
      <webElementGuid>796dbd89-cbaf-44e1-83d6-852fe1503828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sbmtbutton']</value>
      <webElementGuid>bf432176-f49e-403b-867f-b9ecf7311af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validateSubmit']/input[4]</value>
      <webElementGuid>45e98436-612e-414e-bebe-8c5fdd878e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>cb460d1f-44cb-4ff3-9b51-e4bda64a8e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sbmtbutton' and @type = 'submit']</value>
      <webElementGuid>1fe63b76-a0db-44bb-88da-6bed8d2916ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
