<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Authentication Result_acssubmit</name>
   <tag></tag>
   <elementGuidId>f4f562f2-afac-499d-bbdd-abb89112b066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acssubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acssubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8123d4b7-bf45-48b7-8793-f957b209ec85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acssubmit</value>
      <webElementGuid>f23616e9-07d6-4c33-9399-7bc656396e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>09d82c7f-24a4-4c41-bbcd-1b7e2d53ae55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>1718bee2-1b49-4b15-8820-c482b9f2f9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acssubmit&quot;)</value>
      <webElementGuid>10f27d51-9be8-494a-a5b0-38eaee3397c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Processing Payment/iframe_challengeFrame</value>
      <webElementGuid>9c04ae6c-765a-4f17-a654-81fc59b1ba1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acssubmit']</value>
      <webElementGuid>25d3e162-13a8-45f6-978f-c58c64cbc658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContainerContent']/center/form/table/tbody/tr[4]/td/input</value>
      <webElementGuid>96ea28da-9f97-4d3a-a31f-0a0322ca16be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a8f5862c-c43f-44e3-9a44-04c6098817a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'acssubmit' and @type = 'submit']</value>
      <webElementGuid>f7921297-7d81-4eef-836f-a74ea176f446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
